/**
 * The type of service we have delivered.
 */
export enum ServiceType {
  Coaching = "coaching",
  Consulting = "consulting", // Soll für Freelancing/Projekt Mithilfe stehen, als Aufträge, deren Endkunde nicht meiner war
  ClientProject = "clientProject",
  OSS = "openSource",
}

export enum TaskType {
  APIDesign = "apidesign",
  AppStore = "appStore", // Manage app store account, releases & content and beta testing & versioning
  CloudHosting = "cloudhosting",
  Coaching = "coaching",
  Coding = "coding",
  CustomerService = "customerservice", // = ServiceDesk
  DatabaseCoding = "database",
  DataModeling = "datamodelling",
  Design = "design",
  DesignSystem = "designSystem",
  Documentation = "documentation",
  Frontend = "frontend",
  ITArchitecture = "itarchitecure",
  Prototyping = "prototyping",
  Requirements = "requirements",
  Rollout = "rollout", // = Deployment
  SEO = "seo",
  SoundDesign = "sounddesign",
  UX = "ux",
  Visualization = "visualization",
  Writing = "writing",
  MusicProduction = "musicProduction",
  Composing = "composing",
}

export enum DeliveryType {
  Desktop = "desktop",
  MobileApp = "app",
  PWA = "pwa",
  SPA = "spa",
  Website = "website",
  Content = "content",
  Library = "library",
  MasterRecording = "masterRecording",
}

export enum ClientSize {
  Corporate = "corporate",
  Midsized = "kmu",
  SmallBusiness = "smallBusiness",
}

export interface Project {
  customer: string;
  industry: string;
  deliveryTypes: DeliveryType[];
  serviceType: ServiceType;
  taskTypes: TaskType[];
  title: string;
  toolsUsed: string[];
  year: number;
  timestamp?: string; // TODO: Make requried and use to sort projects chronologically
  description?: string;
  clientSize?: ClientSize;
  links?: string[];
}

export const projects: Project[] = [
  {
    customer: "Auftakt Medien e.K.",
    title: "Entwicklung der Onlinepräsenz der Klaus Günther GmbH",
    industry: "Industrie",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2015,
    timestamp: "2015-10-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: [
      "Wordpress",
      "MySQL",
      "Bootstrap",
      "HTML",
      "CSS",
      "Javascript",
      "jQuery",
      "PHP",
    ],
    links: ["https://www.kguenther.de"],
  },
  {
    customer: "Auftakt Medien e.K.",
    title: "Google Maps Integration für die Cassis Manufaktur",
    industry: "Nahrungsmittel",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2015,
    timestamp: "2015-03-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: [
      "Wordpress",
      "MySQL",
      "HTML",
      "CSS",
      "Javascript",
      "jQuery",
      "PHP",
      "Google Maps",
    ],
    links: ["https://www.cassismanufaktur.de"],
  },
  {
    customer: "Auftakt Medien e.K.",
    title: "Onlinepräsenz für Rechtsanwalt Vogel GmbH",
    industry: "Rechtsberatung",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2014,
    timestamp: "2014-05-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: [
      "Wordpress",
      "MySQL",
      "HTML",
      "CSS",
      "Javascript",
      "jQuery",
      "PHP",
      "AngularJS",
      "Bootstrap",
    ],
    description: `Entwicklung einer responsive Website mit CMS.`,
    links: ["http://www.rv-gmbh.de"],
  },
  {
    customer: "Auftakt Medien e.K.",
    title: "Entwicklung einer SEO-optimierten SPA für Grüner Baum Sinsheim",
    industry: "Gastronomie",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding, TaskType.SEO],
    year: 2015,
    timestamp: "2015-04-01",
    deliveryTypes: [DeliveryType.Website, DeliveryType.SPA],
    toolsUsed: [
      "Wordpress",
      "MySQL",
      "Bootstrap",
      "HTML",
      "CSS",
      "Javascript",
      "AngularJS",
      "PHP",
    ],
    description: `Entwicklung einer SPA die trotzdem gute SEO-Ergebnisse liefert zu einer Zeit als die Suchmaschinen-Bots noch kein Javascript interpretierten. Hierzu wurde eine PHP-Komponente mit einer Weiche für Bots entwickelt, welche dem Bot die vollständig gerenderte Website lieferte und somit Javascript unnötig machte.`,
    links: ["https://www.gruenerbaum-sinsheim.de"],
  },
  {
    customer: "Auftakt Medien e.K.",
    title:
      "Entwicklung einer Website mit Immobilien-Portal für Wohnbau Oberriexingen",
    industry: "Immobilien",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2014,
    timestamp: "2014-04-01",
    deliveryTypes: [DeliveryType.Website, DeliveryType.SPA],
    toolsUsed: [
      "Wordpress",
      "MySQL",
      "Bootstrap",
      "HTML",
      "CSS",
      "Javascript",
      "jQuery",
      "PHP",
      "SASS",
    ],
    description: `Entwicklung einer SEO-optimierten AJAX-Website mit client-seitigem Tausch von Inhalten, die per AJAX gelesen werden.`,
    links: ["https://www.wohnbau-oberriexingen.de"],
  },
  {
    customer: "Sigurd Roscher",
    title: "Online-Portfolio für Barbara Bonisolli Food-Fotografin",
    industry: "Marketing",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2016,
    timestamp: "2016-09-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: [
      "Wordpress",
      "MySQL",
      "Bootstrap",
      "HTML",
      "CSS",
      "Javascript",
      "PHP",
    ],
    description: `Entwicklung eines grafisch schlichten aber anspruchsvollen Online-Portfolios für Barbara Bonisolli - Food Fotografin u.a. für Mc Donalds`,
    links: ["http://www.bonisolli.de"],
  },
  {
    customer: "Sigurd Roscher",
    title: "Entwicklung der WeinKulturGaden Thüngersheim Website",
    industry: "Kultur",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding, TaskType.CloudHosting],
    year: 2015,
    timestamp: "2015-03-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ["Foundation CSS", "HTML", "CSS", "Javascript"],
    description: `Websiteentwicklung mit hohem Anspruch an Emotion und Bildmaterial.`,
    links: ["https://weinkulturgaden.de"],
  },
  {
    customer: "Sigurd Roscher",
    title: "Entwicklung der Website der Kieferchirurgie Regensburg",
    industry: "Medizin",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding, TaskType.CloudHosting],
    year: 2017,
    timestamp: "2017-10-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ["HTML", "CSS", "Javascript"],
    description: `Entwicklung der Onlinepräsenz der Kieferchhirurgie Regensburg mit vielen ästhetischen Animationen und emotionalen Bildern.`,
    links: ["http://kieferchirurgie-regensburg.de"],
  },
  {
    customer: "Sigurd Roscher",
    title: "Online-Rechner Green LED Dot",
    industry: "Energie",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2014,
    timestamp: "2014-07-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ["HTML", "CSS", "Javascript"],
    description: `Entwicklung ein Online-Rechners für die Berechnung von Ersparnissen durch den Wechsel zu LED Birnen.`,
    links: ["http://greenleddot.com/ersparnis-rechner/"],
  },
  {
    customer: "Matthias Max",
    title: "Entwicklung der Website Trackpool",
    industry: "Musik",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [TaskType.Coding, TaskType.Design, TaskType.SEO, TaskType.UX],
    year: 2001,
    timestamp: "2001-01-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ["HTML", "CSS", "Javascript"],
    description: `Entwicklung einer Website zum Austausch von Musik und zum Erstellen von Künstlerprofilen.`,
  },
  {
    customer: "Mind One",
    title: "Entwicklung einer Website für mein eigenes EDM-Projekt Mind One",
    industry: "Musik",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.SEO,
      TaskType.UX,
      TaskType.CloudHosting,
    ],
    year: 2001,
    timestamp: "2001-12-31",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ["HTML", "CSS", "Javascript", "Photoshop"],
    description: `Meine erste Website überhaupt war für mein EDM-Musikprojekt Mind One. Es ging darum, mich als Künstler bekannter zu machen und mit Fans in Kontakt zu treten. Ich habe das Design, die Programmierung und das Hosting selber übernommen.`,
  },
  {
    customer: "Breathe Music",
    title: "Entwickeln einer Website für Breathe Music",
    industry: "Musik",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.SEO,
      TaskType.UX,
      TaskType.CloudHosting,
    ],
    year: 2005,
    timestamp: "2005-06-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ["HTML", "CSS", "Javascript", "Photoshop", "Wordpress", "CMS"],
    description: `Entwickeln einer CMS-basierten Website für Breathe Music mit Multimedia-Features wie MP3-Player und Slideshow.`,
  },
  {
    customer: "Superstreem Media",
    title: `Entwicklung und Betrieb einer Website für Superstreem Media`,
    industry: "Musik",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.SEO,
      TaskType.UX,
      TaskType.CloudHosting,
    ],
    year: 2007,
    timestamp: "2007-06-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ["HTML", "CSS", "Javascript", "Photoshop"],
    description: `Entwicklung und Betrieb einer Website für Superstreem Media mit Multimedia-Features wie MP3-Player und Slideshow.`,
  },
  {
    customer: "Securikett Ulrich & Horn GmbH",
    title: `Entwicklung der Mobile-App "CODIKETT" zur Graumarktaufdeckung iOS und Android`,
    industry: "Logistik",
    clientSize: ClientSize.Midsized,
    serviceType: ServiceType.ClientProject,
    taskTypes: [TaskType.Coding, TaskType.AppStore],
    year: 2014,
    timestamp: "2014-06-01",
    deliveryTypes: [DeliveryType.MobileApp],
    toolsUsed: [
      "HTML",
      "CSS",
      "Javascript",
      "Ionic",
      "Cordova",
      "SASS",
      "AngularJS",
      "REST API",
      "XCode",
      "Android Studio",
    ],
    description: `Entwicklung einer Mobile-App zum Lesen von GS 1 Datamatrix Codes mit versteckten Identifiern. Veröffentlichen der App in den Apple und Google App-Stores und pflegen der App-Store Inhalte. Entwickleraccounts für den Kunden anlegen und verwalten. Entwickeln einer Open Source Javascript Komponente zum Lesen von GS 1-spezifischen Datamatrix Codes.`,
  },
  {
    customer: "Securikett Ulrich & Horn GmbH",
    title: `Entwicklung der Mobile-App "MILLEPADIA" für iOS und Android Mobile App`,
    industry: "Logistik",
    clientSize: ClientSize.Midsized,
    serviceType: ServiceType.ClientProject,
    taskTypes: [TaskType.Coding, TaskType.AppStore],
    year: 2016,
    timestamp: "2016-06-01",
    deliveryTypes: [DeliveryType.MobileApp],
    toolsUsed: [
      "HTML",
      "CSS",
      "Javascript",
      "Ionic",
      "Cordova",
      "SASS",
      "AngularJS",
      "XCode",
      "Android Studio",
    ],
    description: `Entwicklung einer Mobile-App zum Lesen von GS 1 Datamatrix Codes mit versteckten Identifiern. Veröffentlichen der App in den Apple und Google App-Stores und pflegen der App-Store Inhalte. Entwickleraccounts für den Kunden anlegen und verwalten. Entwickeln einer Open Source Javascript Komponente zum Lesen von GS 1-spezifischen Datamatrix Codes.`,
  },
  {
    customer: "RTS Steuerberatungsgesellschaft KG",
    title: `Online-Spiel "Tax Hero"für das Recruiting von jungen Mitarbeitern`,
    industry: "Personal",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.Coaching,
      TaskType.SoundDesign,
      TaskType.APIDesign,
      TaskType.CloudHosting,
      TaskType.DataModeling,
      TaskType.ITArchitecture,
      TaskType.Requirements,
      TaskType.Documentation,
    ],
    year: 2015,
    timestamp: "2015-05-01",
    deliveryTypes: [DeliveryType.SPA],
    toolsUsed: [
      "HTML",
      "CSS",
      "Javascript",
      "Ionic",
      "SASS",
      "AngularJS",
      "NodeJS",
      "ExpressJS",
      "REST",
      "MongoDB",
      "NoSQL",
      "Grunt",
      "Gulp",
      "Sketch",
    ],
    description: `Mit dem Online-Spiel sollen spielerisch Bewerber gewonnen werden. Ich habe vom Vertrieb, über das Konzept, den Spielnamen, das Spieldesign sowie der Programmierung, Betrieb und Schulung sämtliche Rollen übernommen.`,
  },
  {
    customer: "Bosch.IO GmbH",
    title: `Erstellen einer Mobile-App "Smart Trunk" zum Öffnen des Kofferraum über das Internet`,
    industry: "Automotive",
    clientSize: ClientSize.Corporate,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.APIDesign,
      TaskType.DataModeling,
      TaskType.Requirements,
      TaskType.Prototyping,
    ],
    year: 2016,
    timestamp: "2016-06-28",
    deliveryTypes: [DeliveryType.MobileApp],
    toolsUsed: [
      "HTML",
      "CSS",
      "Javascript",
      "Ionic",
      "Cordova",
      "SASS",
      "AngularJS",
      "NodeJS",
      "REST",
      "Gulp",
      "Sketch",
    ],
    description: `Für ein internes Innovationsprojekt wurde eine Mobile App für iOS benötigt. Sie sollte Teil des Use Cases "smarter Kofferraum" in Handel und Logistik sein. Es soll aufgezeigt werden, ob solche LÖsungen in Zukunft eingesetzt werden können.`,
    links: ["https://www.youtube.com/watch?v=Xj-AQuP2AOA"],
  },
  {
    customer: "ecce AG Schweiz",
    title: "Entwicklung von 6 Windows Desktop-Apps für das SLA Management",
    industry: "IT-Services",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.APIDesign,
      TaskType.DataModeling,
      TaskType.Requirements,
      TaskType.DatabaseCoding,
      TaskType.Documentation,
      TaskType.ITArchitecture,
      TaskType.Rollout,
      TaskType.Visualization,
    ],
    year: 1999,
    timestamp: "1999-01-01",
    deliveryTypes: [DeliveryType.Desktop],
    toolsUsed: [
      "Visual Basic 6.0",
      "MS SQL-Server",
      "Windows Server",
      "Installshield",
      "Crystal Reports",
      "SQL",
      "Osen UI Framework",
    ],
    description: `Entwicklung von 6 Windows Desktop-Anwendungen für das Management von Service Level Agreements. Erstellen von Setups für Windows mit Installshield. Rollouts organisiert mit IT-Administratoren in Konzernen. Erstellen von Berichten mit Crytsal Reports. Endkunden der Software Postbank, Daimler und andere.`,
  },
  {
    customer: "Qtobe AG Schweiz",
    title:
      "Entwicklung einer Desktop-App mit Visual Basic.Net inkl. Reporting Engine und Migration SQL-Server zu Oracle",
    industry: "IT-Services",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.APIDesign,
      TaskType.DataModeling,
      TaskType.Requirements,
      TaskType.DatabaseCoding,
      TaskType.Documentation,
      TaskType.ITArchitecture,
      TaskType.Rollout,
      TaskType.Visualization,
      TaskType.CustomerService,
    ],
    year: 2001,
    timestamp: "2001-06-01",
    deliveryTypes: [DeliveryType.Desktop],
    toolsUsed: [
      "Visual Basic 6.0",
      "MS SQL-Server",
      "Windows Server",
      "Oracle Database Server",
      "Installshield",
      "Crystal Reports",
      "SQL",
      "Osen UI Framework",
    ],
    description: `Entwicklung der Q-Board IT-Servicemanagement Suite Desktop App für das Verwalten von SLAs (Service Level Agreements). Migration von MY SQL-Server zu Oracle Datenbank. Entwerfen von Tabellen, Views und SQL-Queries, Kunden, welche die Lösung verwenden: Postbank, Commerzbank, Daimler und andere.`, // TODO: Fix customer list
  },
  {
    customer: "Qtobe AG Schweiz",
    title:
      "Migration einer Visual Basic Desktop-Anwendung in eine Microsoft .Net Web-Forms-Anwendung",
    industry: "IT-Services",
    clientSize: ClientSize.Midsized,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.APIDesign,
      TaskType.DataModeling,
      TaskType.Requirements,
      TaskType.DatabaseCoding,
      TaskType.Documentation,
      TaskType.ITArchitecture,
      TaskType.Rollout,
    ],
    year: 2006,
    timestamp: "2006-06-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: [
      "ASP.Net",
      "Visual Basic",
      "WebForms",
      "Windows Server",
      "Oracle Database Server",
      "Crystal Reports",
      "SQL",
    ],
    description: `Migration der bestehenden Q-Board IT-Servicemanagement Suite Web Application in eine Web-Forms-Anwendung basierend auf Microsoft ASP.Net. Die Q-Board IT-Servicemanagement Suite ist eine Software für das Verwalten von SLAs (Service Level Agreements). Kunden, welche die Lösung verwenden: Postbank, Commerzbank, Daimler und andere.`, // TODO: Fix customer list
  },
  {
    customer: "Qtobe AG Schweiz",
    title:
      "Modernisierung einer Microsoft ASP.Net WebForms-Anwendung um REST Schnittstellen und neues UI",
    industry: "IT-Services",
    clientSize: ClientSize.Midsized,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.APIDesign,
      TaskType.DataModeling,
      TaskType.Requirements,
      TaskType.DatabaseCoding,
      TaskType.Documentation,
      TaskType.ITArchitecture,
      TaskType.Rollout,
      TaskType.Coaching,
    ],
    year: 2009,
    timestamp: "2009-06-01",
    deliveryTypes: [DeliveryType.Website, DeliveryType.SPA],
    toolsUsed: [
      "ASP.Net",
      "Visual Basic",
      "WebForms",
      ".Net Web Controller",
      "AJAX",
      "REST",
      "Angular JS",
      "IIS",
      "Windows Server",
      "Oracle Database Server",
      "SQL",
    ],
    description: `Erweiterung der bestehenden Software Q-Board IT-Servicemanagement Suite um REST Schnittstellen für Nutzung modernerer Webtechnologien wie z.B. AngularJS. Coaching von Team-Mitgliedern bzgl. neuer Webtechnologien. Die Q-Board IT-Servicemanagement Suite ist eine Software für das Verwalten von SLAs (Service Level Agreements). Kunden, welche die Lösung verwenden: Postbank, Commerzbank, Daimler und andere.`, // TODO: Fix
  },
  {
    customer: "Bosch.IO Gmbh",
    title: "Gast Blogger zu den Themen IoT & Geschäftsmodelle",
    industry: "IoT",
    clientSize: ClientSize.Corporate,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Writing],
    year: 2016,
    timestamp: "2016-05-01",
    deliveryTypes: [DeliveryType.Content],
    toolsUsed: ["NotePad"],
    description: `Für Bosch.IO habe ich Gast-Beiträge zu den Themen Innovation, Geschäftsmodelle, IoT und weiteren verfasst. Diese wurden im Bosch.IO Blog veröffentlicht.`,
    links: ["https://blog.bosch-si.com/search/matthias%20max"],
  },
  {
    customer: "Mind One",
    title: "Website für einen EDM artist",
    industry: "Musik",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [TaskType.Coding, TaskType.Design, TaskType.SEO, TaskType.UX],
    year: 2001,
    timestamp: "1999-01-01",
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ["HTML", "CSS", "Javascript", "Photoshop"],
    description: `Programmieren einer Website für mein EDM Projekt "Mind One", um die Bekanntheit zu erhöhen und den Kontakt mit Lizenznehmern und Fans herzustellen.`,
  },
  {
    customer: "Mind One",
    title: "EDM Artist und Musikproduzent",
    industry: "Musik",
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.SoundDesign,
      TaskType.Composing,
      TaskType.MusicProduction,
      TaskType.Design,
    ],
    year: 1999,
    timestamp: "1999-01-01",
    deliveryTypes: [DeliveryType.MasterRecording],
    toolsUsed: [
      "Steinberg Cubase",
      "Synthesizers",
      "Photoshop",
      "Mischpult",
      "Studiotechnik",
    ],
    description: `Mein EDM Artist-projekt "Mind One" wurde von vielen Bekannten DJs wie Paul van Dyk, Tiesto, Armin van Buuren und Ferry Corsten unterstützt. Die musikalischen Rechte wurden durch Lizensierung mit Lizenznehmern wie Sony, etc (Compilations) monetär ausgewertet. Die Verlagstätigkeiten wurden selber übernommen und mit der GEMA abgerechnet. Alle Grafikleistungen wie Plattencover, Logo und Werbebanner wurden selbst erstellt.`,
  },
  {
    customer: "Open Source",
    title:
      "GS1.js: Javascript GS1 barcode content parser for NodeJS and the browser",
    industry: "Software",
    serviceType: ServiceType.OSS,
    taskTypes: [TaskType.Coding],
    year: 2016,
    timestamp: "2016-05-02",
    deliveryTypes: [DeliveryType.Library],
    toolsUsed: ["Javascript", "Typescript", "Gulp"],
    description: `GS1JS is a Javascript GS1 barcode content parser for NodeJS and the browser written in Typescript.`,
    links: ["https://github.com/bitflower/gs1js"],
  },
  {
    customer: "Open Source",
    title:
      "Stencil-Lerna: A starter kit for developing Stencil-PWAs in a lerna monorepo",
    industry: "Software",
    serviceType: ServiceType.OSS,
    taskTypes: [TaskType.Coding],
    year: 2019,
    timestamp: "2019-06-02",
    deliveryTypes: [DeliveryType.Library],
    toolsUsed: [
      "Javascript",
      "Typescript",
      "StencilJS",
      "NodeJS",
      "Lerna",
      "Monorepo",
      "Rollup",
    ],
    description: `A starter kit for developing PWAs in a lerna monorepo including a web-component design-system in Typescript.`,
    links: ["https://github.com/bitflower/stencil-lerna"],
  },
  {
    customer: "Trademarketing Service GmbH",
    title: "Entwicklung eines Design Systems für eine POS-Management Software",
    industry: "Handel/POS",
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.UX,
      TaskType.Design,
      TaskType.Frontend,
      TaskType.Prototyping,
      TaskType.DesignSystem,
    ],
    year: 2016,
    timestamp: "2016-05-01",
    deliveryTypes: [DeliveryType.SPA],
    toolsUsed: [
      "HTML",
      "CSS",
      "Javascript",
      "Typescript",
      "Sketch",
      "Bootstrap",
    ],
    description: `Entwicklung eines HTML/CSS/Javascript Design Systems für eine neue POS-Management Software. Über die Software können Mitarbeiter Zeiten buchen, Aufträge bearbeiten und Einsätze planen. Es wurde Kein Javascript-Framework eingesetzt.`,
    links: ["https://one-promoterweb.tmsgmbh.de"],
  },
];
