import {
  ClientSize,
  DeliveryType,
  Project,
  ServiceType,
  TaskType,
} from './types';

export const projects: Project[] = [
  {
    customer: 'Premium manufacturer of energy storage management systems',
    title: 'Development of a OCPP-Management frontend for support agents',
    industry: 'Smart Energy / E-Mobility',
    clientSize: ClientSize.Midsized,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Frontend,
      TaskType.ITArchitecture,
      TaskType.Requirements,
      TaskType.UX,
      TaskType.QA,
    ],
    year: 2023,
    timestamp: '2023-09-01',
    duration: [4, 'months'],
    deliveryTypes: [DeliveryType.ITArchitecture, DeliveryType.ProductOwnership],
    toolsUsed: [
      'Azure DevOps',
      'Figma',
      'React',
      'Typescript',
      'OpenAPI',
      'MIRO',
    ],
    description: `Development of a web-based management frontend for support agents of the energy storage management system. The goal was to provide the support agents with a tool that enables them to manage the customer's charging infrastructure in a more efficient way. The challenge was to prepare the components in a way so they can be re-used later in different scenarios accross the company e.g. in the existing portal. The generic approach was achieved by decoulping core functionality in separate package and importing them into the main app. The frontend was developed with React and Typescript. The development was done in a team of 4 developers and 2 QA agents. The requirements were collected in close cooperation with the support agents. The development process was agile with 3-week sprints. The UX was visualized in Figma. The API was designed with OpenAPI. The backlog was managed Azure DevOps and later in JIRA. The project included stakeholder communication with the VP of Cloud Services and the internal Product Owners.`,
  },
  {
    customer: 'Premium manufacturer of energy storage management systems',
    title: 'Architecture Audit, Documentation and Change Management-Process',
    industry: 'Smart Energy',
    clientSize: ClientSize.Midsized,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.ITArchitecture,
      TaskType.Documentation,
      TaskType.Visualization,
      TaskType.Rollout,
      TaskType.QA,
    ],
    year: 2024,
    timestamp: '2024-01-01',
    duration: [6, 'months'],
    deliveryTypes: [DeliveryType.ITArchitecture],
    toolsUsed: [
      'Confluence',
      'Structurizr',
      'Jira',
      'Deployment Artefacts',
      'Docker',
    ],
    description: `Audit of the existing architecture of the energy storage management system. Documentation of the architecture and and setting up of the change management process with ADRs (Architecture Decision Records). The goal was to make the architecture more transparent and to enable the development teams to make changes more efficiently. And semi-automated approach was taken by using Structurizr as a tool to visualize the architecture and to generate documentation. The deployment artefacts were dockerized and the deployment process of the documentation was automated. Stakeholder communication with VP of Cloud Services and internal IT Architect.`,
  },
  {
    customer: 'E-Mobility Charging Solution Provider',
    title:
      'Agile development of features for a B2B Charging Solution between E-Mobility and Smart Energy',
    industry: 'E-Mobility',
    clientSize: ClientSize.Corporate,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.ProductOwner,
      TaskType.DataModeling,
      TaskType.APIDesign,
      TaskType.Design,
      TaskType.ITArchitecture,
      TaskType.Requirements,
      TaskType.UX,
      TaskType.TeamLead,
      TaskType.Manager,
      TaskType.Refinements,
      TaskType.Sprintplaning,
      TaskType.Roadmap,
    ],
    year: 2021,
    timestamp: '2021-09-01',
    duration: [2, 'years'],
    deliveryTypes: [DeliveryType.ProductOwnership],
    toolsUsed: [
      'React',
      'NodeJS',
      'Microservices',
      'Azure DevOps',
      'Figma',
      'Google Cloud',
      'Terraform',
      'NestJS',
      'ExpressJs',
      'Typescript',
      'Design System',
      'Code Reviews',
      'Refactoring',
      'LeSS',
      'Swagger',
      'API-First',
      'OCPP',
      'Mural',
      'OKR',
      'User Research',
      'User Testing',
    ],
    description: `As a technical Product Manager and Team Lead of 5 developers and a UX, I had the E2E responsibility for the development of RFID card management, charging process authorization, extended role & rights system, roaming and compensation tariff management service, and dashboard/reporting functions. The starting point was the analysis/migration of the charging infrastructure of one of the largest premium automotive brands from one CSMS backend to another. I derived feature deltas, planned features, developed a roadmap, and coordinated with other stakeholders. In addition, as part of the planning of the implementation, central architectural adjustments were coordinated and implemented with up to 7 teams. Regular, company-wide season plannings were carried out and topics were planned based on OKRs (Objectives and Key Results). Agile process with UX prototyping and rolling releases, 5 new Typescript/NestJS microservices developed. Compilation of the team including writing the tenders, interviews, participant selection, and onboarding.`,
  },
  {
    customer: 'Automotive OEM',
    title:
      'Development of a process control tool for WLTP and NEFZ vehicle certification',
    industry: 'Automotive',
    clientSize: ClientSize.Corporate,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.DataModeling,
      TaskType.Frontend,
      TaskType.Visualization,
      TaskType.APIDesign,
      TaskType.ITArchitecture,
      TaskType.Requirements,
      TaskType.Coaching,
      TaskType.UX,
      TaskType.Documentation,
      TaskType.UnitTests,
      TaskType.QA,
    ],
    year: 2018,
    timestamp: '2021-05-01',
    duration: [3, 'years'],
    deliveryTypes: [DeliveryType.SPA],
    toolsUsed: [
      'Angular 11',
      'NodeJS',
      'Microservices',
      'Azure DevOps',
      'Angular Material',
      'RxJS',
      'HTML',
      'CSS',
      'Javascript',
      'Typescript',
      'Sketch',
      'SQL-Server',
      'Figma',
      'Design System',
      'Code Reviews',
      'Refactoring',
      'Jest',
      'SAFe',
      'Swagger',
    ],
    description: `Broad-based consulting services in an Angular/Microservice development project with about 40 employees and Board-of-Management attention. As Frontend Lead, I coordinated the requirements with stakeholders, backend leads, and the frontend team. I empowered junior developers in the use of Angular 11+. I introduced newcomers to the codebase. I implemented and further developed the design system and essential central components. My role also included enhancing cross-team communication. For this purpose, I scheduled weekly developer/PO/Lead meetings (Dev-Insights) to address topics. It was my responsibility to maintain UI/UX consistency both during development and in the conceptual phase of new features. Wireframes and mockups were realized in Figma for a better conveyance of the later look & feel of the application. I wrote automated component unit tests. The project was conducted with SAFe.`,
  },
  {
    customer: 'bitflower e.K.',
    title: 'Development of the Low-Code Platform CaseOS',
    industry: 'SaaS',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.DataModeling,
      TaskType.Frontend,
      TaskType.Visualization,
      TaskType.APIDesign,
      TaskType.AppStore,
      TaskType.CloudHosting,
      TaskType.DatabaseCoding,
      TaskType.ITArchitecture,
      TaskType.Requirements,
      TaskType.Rollout,
      TaskType.UX,
      TaskType.Design,
      TaskType.DesignSystem,
      TaskType.UnitTests,
      TaskType.QA,
    ],
    year: 2019,
    timestamp: '2022-01-01',
    duration: [2, 'years'],
    deliveryTypes: [DeliveryType.SPA, DeliveryType.MobileApp, DeliveryType.PWA],
    toolsUsed: [
      'StencilJS',
      'NodeJS',
      'ExpressJS',
      'Ionic',
      'Redux',
      'CapacitorJS',
      'Typescript',
      'HTML',
      'CSS',
      'Javascript',
      'Sketch',
      'Shoelace Web Components',
      'MongoDB',
      'NoSQL',
      'REST',
      'WebSocket',
      'Socket.IO',
      'Jest',
      'Swagger',
    ],
    description: `After 12 years of custom software development for corporations and medium-sized businesses, we decided to channel our expertise into a product. Our product, CaseOS, is a digital toolkit that allows applications, frontends, and apps to be dynamically developed with a WYSIWYG editor. However, the user is not limited in terms of customization. On the contrary. The system is designed from the ground up for whitelabeling and expansion. The user's own CI/CD can be easily implemented, and individual extensions can be developed by themselves. Both in the frontend and in the backend, there are no limits. Neither in the choice of technology nor in the platform. Since the system is completely based on web technologies, all channels can be served from it: Web, PWA, App, Desktop, and theoretically even embedded systems.`,
  },
  {
    customer: 'Auftakt Medien e.K.',
    title:
      'Development of a real-estate help-resource mobile app for iOS and Android including maintenance notification',
    industry: 'Real Estate',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.DataModeling,
      TaskType.Frontend,
      TaskType.Visualization,
      TaskType.APIDesign,
      TaskType.AppStore,
      TaskType.CloudHosting,
      TaskType.DatabaseCoding,
      TaskType.ITArchitecture,
      TaskType.Requirements,
      TaskType.Rollout,
      TaskType.QA,
    ],
    year: 2020,
    timestamp: '2020-02-01',
    duration: [3, 'months'],
    deliveryTypes: [DeliveryType.SPA, DeliveryType.MobileApp, DeliveryType.PWA],
    toolsUsed: [
      'StencilJS',
      'NodeJS',
      'ExpressJS',
      'Ionic',
      'Redux',
      'CapacitorJS',
      'Typescript',
      'HTML',
      'CSS',
      'Javascript',
      'Sketch',
      'Shoelace Web Components',
      'MongoDB',
      'NoSQL',
      'Swagger',
    ],
    description: `To enhance customer loyalty and transition the existing paper building manual, an iOS and Android app was developed. In addition to the reprocessed content of the existing household manual, it offers the functionality of alerting for recurring maintenance. This includes, for example, green roofing, house water filters, ventilation systems, and others. The end customer can independently change and add new content through the No-Code WYSIWYG editor. The app works offline and synchronizes in real-time with the server to load new content and downloads (PDF) as soon as it is online. Files and content are stored on the local device filesystem.`,
  },
  {
    customer: 'bitflower e.K.',
    title: 'Development of a configurable NodeJS OPC UA REST/WebSocket Adapter',
    industry: 'IoT',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.Requirements,
      TaskType.APIDesign,
      TaskType.DevOps,
    ],
    year: 2020,
    timestamp: '2020-12-31',
    duration: [1, 'months'],
    deliveryTypes: [DeliveryType.Library],
    toolsUsed: [
      'NodeJS',
      'ExpressJS',
      'Typescript',
      'JSON',
      'Javascript',
      'REST',
      'Industry 4.0',
      'OPC UA',
      'Siemens S7 PLC',
      'PM2 Task Manager',
    ],
    description: `A configurable OPC-UA adapter was written that reads or subscribes to data from OPC-UA sources, interprets the data, checks it, and if necessary, transforms it. The data is sent to the target application via REST/WebSocket. In the event of a failure of the target system, the data is buffered in the adapter and sent again at the next start.`,
  },
  {
    customer: 'Remondis Süd GmbH',
    title:
      'Development of a production KPI dashboard for bale presses with OPC UA (IIoT)',
    industry: 'IoT',
    clientSize: ClientSize.Midsized,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.DataModeling,
      TaskType.Design,
      TaskType.Frontend,
      TaskType.Requirements,
      TaskType.UX,
      TaskType.Visualization,
      TaskType.APIDesign,
      TaskType.CloudHosting,
      TaskType.Coaching,
      TaskType.DevOps,
      TaskType.QA,
    ],
    year: 2021,
    timestamp: '2021-02-01',
    duration: [3, 'months'],
    deliveryTypes: [DeliveryType.SPA],
    toolsUsed: [
      'StencilJS',
      'NodeJS',
      'ExpressJS',
      'Ionic',
      'Redux',
      'CapacitorJS',
      'Typescript',
      'HTML',
      'CSS',
      'Javascript',
      'Sketch',
      'Shoelace Web Components',
      'Chart.js',
      'MongoDB',
      'NoSQL',
      'Industry 4.0',
      'OPC UA',
      'Sentry.IO',
      'Swagger',
    ],
    description: `Based on the Low-Code platform CaseOS, a dashboard was developed to visualize the daily bale production numbers. A monthly and yearly view also allows the viewer to carry out controlling or planning. They can change decisive KPIs (bales/day, average working hours/hour, or working days/month) in real-time and view the effects. The data is pushed in real-time from the press to the browser without the user's active intervention and is retrieved from the Siemens S7 via OPC UA. The users were trained after commissioning.`,
  },
  {
    customer: 'Daimler (Sub-Contract)',
    title:
      'Concept & Development of a user-friendly drag-and-drop web tool for designing data tables and forms.',
    industry: 'Automotive',
    clientSize: ClientSize.Corporate,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.DataModeling,
      TaskType.Design,
      TaskType.Frontend,
      TaskType.Requirements,
      TaskType.UX,
      TaskType.Visualization,
      TaskType.APIDesign,
    ],
    year: 2017,
    timestamp: '2017-07-01',
    duration: [6, 'months'],
    deliveryTypes: [DeliveryType.SPA],
    toolsUsed: [
      '.Net WebApi',
      'Oracle Database',
      'AngularJS',
      'HTML',
      'CSS',
      'Javascript',
      'Typescript',
      'Sketch',
      'Drag n Drop',
    ],
  },
  {
    customer: 'Commerzbank (Sub-Contract)',
    title:
      'Development of a dynamic, configurable & web-based dashboard framework.',
    industry: 'Finance',
    clientSize: ClientSize.Corporate,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.DataModeling,
      TaskType.Design,
      TaskType.Frontend,
      TaskType.Requirements,
      TaskType.UX,
      TaskType.Visualization,
      TaskType.APIDesign,
    ],
    year: 2016,
    timestamp: '2016-07-01',
    duration: [4, 'months'],
    deliveryTypes: [DeliveryType.SPA],
    toolsUsed: [
      '.Net WebApi',
      'REST',
      'Oracle Database',
      'AngularJS',
      'HTML',
      'CSS',
      'Javascript',
      'Typescript',
      'Sketch',
      'Chart.js',
    ],
    description: `Development of a dashboard system that allows end users to create their own evaluations of KPIs (self-service). Semi-automated creation of SQL statements. Drag-and-drop editor for widget placement and size. Supports various chart types and can be combined.`,
  },
  {
    customer: 'Auftakt Medien e.K.',
    title: 'Development of the online presence for Klaus Günther GmbH',
    industry: 'Industry',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2015,
    timestamp: '2015-10-01',
    duration: [2, 'months'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: [
      'Wordpress',
      'MySQL',
      'Bootstrap',
      'HTML',
      'CSS',
      'Javascript',
      'jQuery',
      'PHP',
    ],
    links: ['https://www.kguenther.de'],
  },
  {
    customer: 'Auftakt Medien e.K.',
    title: 'Google Maps Integration for Cassis Manufaktur',
    industry: 'Food',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2015,
    timestamp: '2015-03-01',
    duration: [2, 'days'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: [
      'Wordpress',
      'MySQL',
      'HTML',
      'CSS',
      'Javascript',
      'jQuery',
      'PHP',
      'Google Maps',
    ],
    links: ['https://www.cassismanufaktur.de'],
  },
  {
    customer: 'Auftakt Medien e.K.',
    title: 'Online presence for Rechtsanwalt Vogel GmbH',
    industry: 'Legal Consulting',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2014,
    timestamp: '2014-05-01',
    duration: [3, 'months'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: [
      'Wordpress',
      'MySQL',
      'HTML',
      'CSS',
      'Javascript',
      'jQuery',
      'PHP',
      'AngularJS',
      'Bootstrap',
    ],
    description: `Development of a responsive website with CMS.`,
    links: ['http://www.rv-gmbh.de'],
  },
  {
    customer: 'Auftakt Medien e.K.',
    title: 'Development of an SEO-optimized SPA for Grüner Baum Sinsheim',
    industry: 'Gastronomy',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding, TaskType.SEO],
    year: 2015,
    timestamp: '2015-04-01',
    duration: [4, 'months'],
    deliveryTypes: [DeliveryType.Website, DeliveryType.SPA],
    toolsUsed: [
      'Wordpress',
      'MySQL',
      'Bootstrap',
      'HTML',
      'CSS',
      'Javascript',
      'AngularJS',
      'PHP',
    ],
    description: `Development of an SPA that still delivers good SEO results at a time when search engine bots did not yet interpret JavaScript. For this purpose, a PHP component with a switch for bots was developed, which provided the bot with the fully rendered website, thus making JavaScript unnecessary.`,
    links: ['https://www.gruenerbaum-sinsheim.de'],
  },
  {
    customer: 'Auftakt Medien e.K.',
    title:
      'Development of a website with a real estate portal for Wohnbau Oberriexingen',
    industry: 'Real Estate',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2014,
    timestamp: '2014-04-01',
    duration: [5, 'months'],
    deliveryTypes: [DeliveryType.Website, DeliveryType.SPA],
    toolsUsed: [
      'Wordpress',
      'MySQL',
      'Bootstrap',
      'HTML',
      'CSS',
      'Javascript',
      'jQuery',
      'PHP',
      'SASS',
    ],
    description: `Development of an SEO-optimized AJAX website with client-side content swapping, which is read via AJAX.`,
    links: ['https://www.wohnbau-oberriexingen.de'],
  },
  {
    customer: 'Sigurd Roscher',
    title: 'Online portfolio for Barbara Bonisolli, food photographer',
    industry: 'Marketing',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2016,
    timestamp: '2016-09-01',
    duration: [1, 'months'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: [
      'Wordpress',
      'MySQL',
      'Bootstrap',
      'HTML',
      'CSS',
      'Javascript',
      'PHP',
    ],
    description: `Development of a graphically simple but sophisticated online portfolio for Barbara Bonisolli - food photographer, including for Mc Donalds.`,
    links: ['http://www.bonisolli.de'],
  },
  {
    customer: 'Sigurd Roscher',
    title: 'Development of the WeinKulturGaden Thüngersheim website',
    industry: 'Culture',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding, TaskType.CloudHosting],
    year: 2015,
    timestamp: '2015-03-01',
    duration: [1, 'months'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ['Foundation CSS', 'HTML', 'CSS', 'Javascript'],
    description: `Website development with a high demand for emotion and imagery.`,
    links: ['https://weinkulturgaden.de'],
  },
  {
    customer: 'Sigurd Roscher',
    title: 'Development of the website for Kieferchirurgie Regensburg',
    industry: 'Medicine',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding, TaskType.CloudHosting],
    year: 2017,
    timestamp: '2017-10-01',
    duration: [3, 'weeks'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ['HTML', 'CSS', 'Javascript'],
    description: `Development of the online presence for Kieferchirurgie Regensburg with many aesthetic animations and emotional images.`,
    links: ['http://kieferchirurgie-regensburg.de'],
  },
  {
    customer: 'Sigurd Roscher',
    title: 'Online calculator for Green LED Dot',
    industry: 'Energy',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Coding],
    year: 2014,
    timestamp: '2014-07-01',
    duration: [1, 'weeks'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ['HTML', 'CSS', 'Javascript'],
    description: `Development of an online calculator for calculating savings by switching to LED bulbs.`,
    links: ['http://greenleddot.com/ersparnis-rechner/'],
  },
  {
    customer: 'Matthias Max',
    title: 'Development of the Trackpool website',
    industry: 'Music',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [TaskType.Coding, TaskType.Design, TaskType.SEO, TaskType.UX],
    year: 2001,
    timestamp: '2001-01-01',
    duration: [2, 'years'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ['HTML', 'CSS', 'Javascript'],
    description: `Development of a website for music exchange and creation of artist profiles.`,
  },
  {
    customer: 'Breathe Music',
    title: 'Development of a website for Breathe Music',
    industry: 'Music',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.SEO,
      TaskType.UX,
      TaskType.CloudHosting,
    ],
    year: 2005,
    timestamp: '2005-06-01',
    duration: [2, 'years'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ['HTML', 'CSS', 'Javascript', 'Photoshop', 'Wordpress', 'CMS'],
    description: `Development of a CMS-based website for Breathe Music with multimedia features such as MP3 player and slideshow.`,
  },
  {
    customer: 'Superstreem Media',
    title: `Development and operation of a website for Superstreem Media`,
    industry: 'Music',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.SEO,
      TaskType.UX,
      TaskType.CloudHosting,
    ],
    year: 2007,
    timestamp: '2007-06-01',
    duration: [2, 'years'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ['HTML', 'CSS', 'Javascript', 'Photoshop'],
    description: `Development and operation of a website for Superstreem Media with multimedia features such as MP3 player and slideshow.`,
  },
  {
    customer: 'Securikett Ulrich & Horn GmbH',
    title: `Development of the mobile app "CODIKETT" for gray market detection on iOS and Android`,
    industry: 'Logistics',
    clientSize: ClientSize.Midsized,
    serviceType: ServiceType.ClientProject,
    taskTypes: [TaskType.Coding, TaskType.AppStore, TaskType.QA],
    year: 2014,
    timestamp: '2014-06-01',
    duration: [5, 'months'],
    deliveryTypes: [DeliveryType.MobileApp],
    toolsUsed: [
      'HTML',
      'CSS',
      'Javascript',
      'Ionic',
      'Cordova',
      'SASS',
      'AngularJS',
      'REST API',
      'XCode',
      'Android Studio',
    ],
    description: `Development of a mobile app for reading GS 1 Datamatrix codes with hidden identifiers. Publishing the app on Apple and Google app stores and maintaining the app store content. Setting up and managing developer accounts for the client. Development of an open-source JavaScript component for reading GS 1-specific Datamatrix codes.`,
  },
  {
    customer: 'Securikett Ulrich & Horn GmbH',
    title: `Development of the mobile app "MILLEPADIA" for iOS and Android`,
    industry: 'Logistics',
    clientSize: ClientSize.Midsized,
    serviceType: ServiceType.ClientProject,
    taskTypes: [TaskType.Coding, TaskType.AppStore, TaskType.QA],
    year: 2016,
    timestamp: '2016-06-01',
    duration: [3, 'months'],
    deliveryTypes: [DeliveryType.MobileApp],
    toolsUsed: [
      'HTML',
      'CSS',
      'Javascript',
      'Ionic',
      'Cordova',
      'SASS',
      'AngularJS',
      'XCode',
      'Android Studio',
    ],
    description: `Development of a mobile app for reading GS 1 Datamatrix codes with hidden identifiers. Publishing the app on Apple and Google app stores and maintaining the app store content. Setting up and managing developer accounts for the client. Development of an open-source JavaScript component for reading GS 1-specific Datamatrix codes.`,
  },
  {
    customer: 'RTS Steuerberatungsgesellschaft KG',
    title: `Online game "Tax Hero" for recruiting young employees`,
    industry: 'Human Resources',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.Coaching,
      TaskType.SoundDesign,
      TaskType.APIDesign,
      TaskType.CloudHosting,
      TaskType.DataModeling,
      TaskType.ITArchitecture,
      TaskType.Requirements,
      TaskType.Documentation,
      TaskType.QA,
    ],
    year: 2015,
    timestamp: '2015-05-01',
    duration: [7, 'months'],
    deliveryTypes: [DeliveryType.SPA],
    toolsUsed: [
      'HTML',
      'CSS',
      'Javascript',
      'Ionic',
      'SASS',
      'AngularJS',
      'NodeJS',
      'ExpressJS',
      'REST',
      'MongoDB',
      'NoSQL',
      'Grunt',
      'Gulp',
      'Sketch',
      'Cloud',
    ],
    description: `The online game is designed to playfully win applicants. I took on all roles from sales, concept, game name, game design, programming, operation, and training. Offline capability for operation in exhibition halls without internet access. Gamification of recruiting.`,
  },
  {
    customer: 'Bosch.IO GmbH',
    title: `Creation of a mobile app "Smart Trunk" to open the trunk via the internet`,
    industry: 'Automotive',
    clientSize: ClientSize.Corporate,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.APIDesign,
      TaskType.DataModeling,
      TaskType.Requirements,
      TaskType.Prototyping,
    ],
    year: 2016,
    timestamp: '2016-06-28',
    duration: [1, 'weeks'],
    deliveryTypes: [DeliveryType.MobileApp],
    toolsUsed: [
      'HTML',
      'CSS',
      'Javascript',
      'Ionic',
      'Cordova',
      'SASS',
      'AngularJS',
      'NodeJS',
      'REST',
      'Gulp',
      'Sketch',
    ],
    description: `A mobile app for iOS was needed for an internal innovation project. It was supposed to be part of the "smart trunk" use case in trade and logistics. The aim was to demonstrate whether such solutions can be used in the future.`,
    links: ['https://www.youtube.com/watch?v=Xj-AQuP2AOA'],
  },
  {
    customer: 'ecce AG Switzerland',
    title: 'Development of 6 Windows desktop apps for SLA management',
    industry: 'IT-Services',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.APIDesign,
      TaskType.DataModeling,
      TaskType.Requirements,
      TaskType.DatabaseCoding,
      TaskType.Documentation,
      TaskType.ITArchitecture,
      TaskType.Rollout,
      TaskType.Visualization,
      TaskType.QA,
    ],
    year: 1999,
    timestamp: '1999-01-01',
    duration: [3, 'years'],
    deliveryTypes: [DeliveryType.Desktop],
    toolsUsed: [
      'Visual Basic 6.0',
      'MS SQL-Server',
      'Windows Server',
      'Installshield',
      'Crystal Reports',
      'SQL',
      'Osen UI Framework',
    ],
    description: `Development of 6 Windows desktop applications for the management of Service Level Agreements. Creating setups for Windows with Installshield. Organized rollouts with IT administrators in corporations. Creating reports with Crystal Reports. End customers of the software include Postbank, Daimler, and others.`,
  },
  {
    customer: 'Qtobe AG Switzerland',
    title:
      'Development of a Desktop App with Visual Basic.Net including Reporting Engine and Migration from SQL-Server to Oracle',
    industry: 'IT-Services',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.APIDesign,
      TaskType.DataModeling,
      TaskType.Requirements,
      TaskType.DatabaseCoding,
      TaskType.Documentation,
      TaskType.ITArchitecture,
      TaskType.Rollout,
      TaskType.Visualization,
      TaskType.CustomerService,
      TaskType.QA,
    ],
    year: 2001,
    timestamp: '2001-06-01',
    duration: [5, 'years'],
    deliveryTypes: [DeliveryType.Desktop],
    toolsUsed: [
      'Visual Basic 6.0',
      'MS SQL-Server',
      'Windows Server',
      'Oracle Database Server',
      'Installshield',
      'Crystal Reports',
      'SQL',
      'Osen UI Framework',
    ],
    description: `Development of the Q-Board IT Service Management Suite Desktop App for managing SLAs (Service Level Agreements). Migration from MS SQL-Server to Oracle Database. Design of tables, views, and SQL queries. Customers using the solution include: Postbank, Commerzbank, Daimler, and others.`, // TODO: Adjusted customer list
  },

  {
    customer: 'Qtobe AG Switzerland',
    title:
      'Migration of a Visual Basic desktop application into a Microsoft .Net Web-Forms application',
    industry: 'IT-Services',
    clientSize: ClientSize.Midsized,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.APIDesign,
      TaskType.DataModeling,
      TaskType.Requirements,
      TaskType.DatabaseCoding,
      TaskType.Documentation,
      TaskType.ITArchitecture,
      TaskType.Rollout,
      TaskType.QA,
    ],
    year: 2006,
    timestamp: '2006-06-01',
    duration: [5, 'years'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: [
      'ASP.Net',
      'Visual Basic',
      'WebForms',
      'Windows Server',
      'Oracle Database Server',
      'Crystal Reports',
      'SQL',
    ],
    description: `Migration of the existing Q-Board IT Service Management Suite web application into a Web-Forms application based on Microsoft ASP.Net. The Q-Board IT Service Management Suite is software for managing SLAs (Service Level Agreements). Customers using the solution include Postbank, Commerzbank, Daimler, and others.`,
  },
  {
    customer: 'Qtobe AG Switzerland',
    title:
      'Modernization of a Microsoft ASP.Net WebForms application to include REST interfaces and a new UI',
    industry: 'IT-Services',
    clientSize: ClientSize.Midsized,
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.UX,
      TaskType.APIDesign,
      TaskType.DataModeling,
      TaskType.Requirements,
      TaskType.DatabaseCoding,
      TaskType.Documentation,
      TaskType.ITArchitecture,
      TaskType.Rollout,
      TaskType.Coaching,
      TaskType.QA,
    ],
    year: 2009,
    timestamp: '2009-06-01',
    duration: [5, 'years'],
    deliveryTypes: [DeliveryType.Website, DeliveryType.SPA],
    toolsUsed: [
      'ASP.Net',
      'Visual Basic',
      'WebForms',
      '.Net Web Controller',
      'AJAX',
      'REST',
      'Angular JS',
      'IIS',
      'Windows Server',
      'Oracle Database Server',
      'SQL',
    ],
    description: `Extension of the existing Q-Board IT Service Management Suite software to include REST interfaces for using more modern web technologies such as AngularJS. Coaching of team members regarding new web technologies. The Q-Board IT Service Management Suite is software for managing SLAs (Service Level Agreements). Customers using the solution include Postbank, Commerzbank, Daimler, and others.`,
  },
  {
    customer: 'Bosch.IO GmbH',
    title: 'Guest blogger on IoT & business models topics',
    industry: 'IoT',
    clientSize: ClientSize.Corporate,
    serviceType: ServiceType.Consulting,
    taskTypes: [TaskType.Writing],
    year: 2016,
    timestamp: '2016-05-01',
    duration: [2, 'years'],
    deliveryTypes: [DeliveryType.Content],
    toolsUsed: ['NotePad'],
    description: `I wrote guest posts for Bosch.IO on topics such as innovation, business models, IoT, and more. These were published on the Bosch.IO blog.`,
    links: ['https://blog.bosch-si.com/search/matthias%20max'],
  },
  {
    customer: 'Mind One',
    title: 'Development of a website for my EDM project Mind One',
    industry: 'Music',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.Coding,
      TaskType.Design,
      TaskType.SEO,
      TaskType.UX,
      TaskType.CloudHosting,
    ],
    year: 2001,
    timestamp: '2001-12-31',
    duration: [5, 'years'],
    deliveryTypes: [DeliveryType.Website],
    toolsUsed: ['HTML', 'CSS', 'Javascript', 'Photoshop'],
    description: `My very first website was for my EDM music project Mind One. The goal was to promote myself as an artist and connect with fans. I took care of the design, programming, and hosting.`,
    links: ['https://www.discogs.com/de/artist/75223-Mind-One'],
  },
  {
    customer: 'Mind One',
    title: 'EDM Artist and Music Producer',
    industry: 'Music',
    clientSize: ClientSize.SmallBusiness,
    serviceType: ServiceType.ClientProject,
    taskTypes: [
      TaskType.SoundDesign,
      TaskType.Composing,
      TaskType.MusicProduction,
      TaskType.Design,
    ],
    year: 1999,
    timestamp: '1999-01-01',
    duration: [7, 'years'],
    deliveryTypes: [DeliveryType.MasterRecording],
    toolsUsed: [
      'Steinberg Cubase',
      'Synthesizers',
      'Photoshop',
      'Mixing Console',
      'Studio Technology',
    ],
    description: `My EDM artist project "Mind One" was supported by many renowned DJs like Paul van Dyk, Tiesto, Armin van Buuren, and Ferry Corsten. The musical rights were monetized through licensing with licensors like Sony, Warner, or Universal (compilations like Club Rotation). I took care of the publishing activities myself and settled them with GEMA. All graphic services like record covers, logos, and promotional banners were created by myself.`,
  },
  {
    customer: 'Open Source',
    title:
      'GS1.js: Javascript GS1 barcode content parser for NodeJS and the browser',
    industry: 'Open Source',
    serviceType: ServiceType.OSS,
    taskTypes: [TaskType.Coding],
    year: 2016,
    timestamp: '2016-05-02',
    duration: [1, 'weeks'],
    deliveryTypes: [DeliveryType.Library],
    toolsUsed: ['Javascript', 'Typescript', 'Gulp'],
    description: `GS1JS is a Javascript GS1 barcode content parser for NodeJS and the browser written in Typescript.`,
    links: ['https://github.com/bitflower/gs1js'],
  },
  {
    customer: 'Open Source',
    title:
      'Stencil-Lerna: A starter kit for developing Stencil-PWAs in a lerna monorepo',
    industry: 'Open Source',
    serviceType: ServiceType.OSS,
    taskTypes: [TaskType.Coding],
    year: 2019,
    timestamp: '2019-06-02',
    duration: [1, 'weeks'],
    deliveryTypes: [DeliveryType.Library],
    toolsUsed: [
      'Javascript',
      'Typescript',
      'StencilJS',
      'NodeJS',
      'Lerna',
      'Monorepo',
      'Rollup',
    ],
    description: `A starter kit for developing PWAs in a lerna monorepo including a web-component design system in Typescript.`,
    links: ['https://github.com/bitflower/stencil-lerna'],
  },
  {
    customer: 'Trademarketing Service GmbH',
    title: 'Development of a Design System for a POS Management Software',
    industry: 'Retail/POS',
    serviceType: ServiceType.Consulting,
    taskTypes: [
      TaskType.Coding,
      TaskType.UX,
      TaskType.Design,
      TaskType.Frontend,
      TaskType.Prototyping,
      TaskType.DesignSystem,
    ],
    year: 2016,
    timestamp: '2016-05-01',
    duration: [2, 'months'],
    deliveryTypes: [DeliveryType.SPA],
    toolsUsed: [
      'HTML',
      'CSS',
      'Javascript',
      'Typescript',
      'Sketch',
      'Bootstrap',
    ],
    description: `Development of an HTML/CSS/Javascript design system for a new POS management software. Through the software, employees can book times, process orders, and plan deployments. No Javascript framework was used.`,
    links: ['https://one-promoterweb.tmsgmbh.de'],
  },
  {
    customer: 'BMG Rights Management Berlin',
    clientSize: ClientSize.Midsized,
    industry: 'Music',
    serviceType: ServiceType.ClientProject,
    title:
      'Songwriter for renowned artists with number 1 placements and platinum sales',
    year: 2010,
    timestamp: '2010-01-01',
    duration: [4, 'years'],
    deliveryTypes: [DeliveryType.Content, DeliveryType.MasterRecording],
    description: `Songwriter for artists like Christian Stürmer, Beatrice Egli, Glasperlenspiel, and Marco Mengoni. Number 1 in the charts and platinum or gold sales figures in Germany, Switzerland, and Italy.`,
    taskTypes: [TaskType.Composing, TaskType.MusicProduction],
    toolsUsed: [
      'MacBook',
      'Creativity',
      'Music Theory',
      'Research',
      'Steinberg Cubase',
      'Apple Logic Audio',
      'Ableton Live',
      'Native Instruments',
      'Musical Instruments',
      'Music Studio',
    ],
  },
];
